# 应用服务 WEB 访问端口
server:
  port: 8899
  tomcat:
    max-http-form-post-size: 50MB  # 表单提交大小限制
    max-http-header-size: 128KB     # 请求头大小限制
    max-swallow-size: 50MB         # 请求体大小限制
  max-http-request-header-size: 128KB

spring:
  profiles:
    active: local
  security:
    filter:
      order: 10
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tingyue?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: a1234567
    
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-underline: true
      id-type: auto
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hgh.tingyue.entity

jwt:
  secret: your_jwt_secret_key_here_must_be_very_long_at_least_256_bits
  expiration: 86400  # 24小时，单位：秒

# 日志配置
logging:
  level:
    root: INFO
    com.hgh.tingyue: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
  file:
    name: logs/tingyue.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"

# Knife4j配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.hgh.tingyue.controller
  packages-to-scan: com.hgh.tingyue.controller
  paths-to-match: /**

knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
  documents:
    - name: 项目文档
      locations: classpath:docs/*
  basic:
    enable: false

# TODO: 从Github上拉取下来后需要做如下配置
#aliyun:
#  oss:
#    endpoint:
#    accessKeyId:
#    accessKeySecret:
#    bucketName:
#
#  senseVoice:
#    accessKeyId:
#    accessKeySecret:
#  dashscope:
#    api-key: